# -*- coding: utf-8 -*-
"""bert_base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mWF82Z0lKD7LGpW0hD1iriZOF5CxeV4

## Install transformers ##
"""

!pip install transformers

!pip install accelerate -U

import pandas as pd
import numpy as np

"""## Load file ##"""

df = pd.read_csv("/content/SMSSpamCollection",sep="\t", names= ["label", "message"])
df

"""## Feature Extraction ##"""

#X = list(df['message'])   Independent variables
X = list(df['message'])
X

y = list(df['label'])
y

"""### Mapping ##"""

y = pd.get_dummies(y,drop_first=True)['spam']
y

"""## Train-test split ##"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

"""## Import Bert tokenizer ##"""

from transformers import BertTokenizer

model_name="bert-base-uncased"
# Load the BERT large tokenizer
tokenizer = BertTokenizer.from_pretrained(model_name)

"""## Get encodings ##
train the features to the BERT model
"""

train_encodings = tokenizer(X_train, truncation=True, padding=True)
test_encodings = tokenizer(X_test, truncation=True, padding=True)

#train_encodings
#test_encodings

"""## Convert encodings into Dataset objects ##"""

import tensorflow as tf
train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(train_encodings),
    y_train
))
test_dataset = tf.data.Dataset.from_tensor_slices((
    dict(test_encodings),
    y_test
))

#train_dataset

"""## import BERT model ##"""

from transformers import  BertModel, TFTrainer, TFTrainingArguments

training_args = TFTrainingArguments(
    output_dir="./bert-base-imdb",
    num_train_epochs=3,
    evaluation_strategy="steps",
    eval_steps=500,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    save_total_limit=2,
    save_steps=500,
    logging_steps=100,
    remove_unused_columns=False,
    push_to_hub=False,
    report_to="tensorboard",
)

"""# Training the model with TFTrainer #"""

with training_args.strategy.scope():
   model = BertModel.from_pretrained(model_name,from_tf=True)

trainer = TFTrainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=test_dataset             # evaluation dataset
)

trainer.train()

trainer.evaluate(test_dataset)

trainer.predict(test_dataset)

output = trainer.predict(test_dataset)[1]
output